---
title: "4.Exploratory data analysis"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(reshape2)

cohort <- read_csv("data/cohort_shock_twavgpo2.csv")
```

```{r}
cohort$X <- NULL
cohort$first_careunit <- factor(cohort$first_careunit)
cohort$first_wardid <- factor(cohort$first_wardid)
cohort$admission_type <- factor(cohort$admission_type)
cohort$vaso_firstday <- factor(cohort$vaso_firstday)
cohort$gender <- factor(cohort$gender)
cohort$rrt <- as.factor(cohort$rrt)
cohort$comorbidity_cardio <- factor(cohort$comorbidity_cardio)
cohort$comorbidity_vascular <- factor(cohort$comorbidity_vascular)
cohort$comorbidity_neuro <- factor(cohort$comorbidity_neuro)
cohort$comorbidity_pneumo <- factor(cohort$comorbidity_pneumo)
cohort$comorbidity_metabolic <- factor(cohort$comorbidity_metabolic)
cohort$comorbidity_renal <- factor(cohort$comorbidity_renal)
cohort$comorbidity_liver <- factor(cohort$comorbidity_liver)
cohort$comorbidity_cancer <- factor(cohort$comorbidity_cancer)
cohort$noso_vap <- factor(cohort$noso_vap)
cohort$noso_urinary <- factor(cohort$noso_urinary)
cohort$noso_cvc <- factor(cohort$noso_cvc)
cohort$noso_cvc_other <- factor(cohort$noso_cvc_other)
cohort$source_pulm <- factor(cohort$source_pulm)
cohort$source_urogyn <- factor(cohort$source_urogyn)
cohort$source_neuro <- factor(cohort$source_neuro)
cohort$source_dig <- factor(cohort$source_dig)
cohort$source_ost <- factor(cohort$source_ost)
cohort$source_ent <- factor(cohort$source_ent)
cohort$source_card <- factor(cohort$source_card)
cohort$source_skin <- factor(cohort$source_skin)
cohort$source_other <- factor(cohort$source_other)
cohort$death_icu <- factor(cohort$death_icu)
cohort$death_thirtydays <- factor(cohort$death_thirtydays)
cohort$death_hosp <- factor(cohort$death_hosp)
cohort$hypero2 <- factor(cohort$hypero2)
cohort$flag_shock <- factor(cohort$flag_shock)

# Merge Emergency and Urgent admission types
cohort$admission_type <- as.character(cohort$admission_type)
cohort$admission_type[cohort$admission_type %in% c("EMERGENCY", "URGENT")] <- "Emergency/Urgent"
cohort$admission_type <- factor(cohort$admission_type)
levels(cohort$admission_type) <- c("Elective", "Emergency/Urgent")

summary(cohort)
```

Replace anonymized ages (above 300 y/o) with 89

```{r}
cohort <- cohort %>%
  mutate(admission_age = replace(admission_age, admission_age > 300, 89))
```

# Continuous variables

```{r}
cohort %>%
  keep(is.numeric) %>%
  select(-subject_id, -hadm_id, -icustay_id) %>%
  map_df(.f = ~ broom::tidy(round(summary(.x), 2)), .id = "variable") %>%
  kable(caption = "Continuous variables",
        col.names = c("Variables", "Min", "25 %", "Median", "Mean", "75 %", "Max", "NA")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r message=FALSE, warning=FALSE, dpi=400}
cohort %>%
  keep(is.numeric) %>%
  select(-subject_id, -hadm_id, -icustay_id) %>%
  melt() %>%
  ggplot(aes(x = value)) +
  facet_wrap(~ variable, scales = "free", ncol = 5) +
  geom_histogram(fill = "#455a64") +
  labs(x = "Continuous variables", y ="")
```

# Categorial variables

```{r message=FALSE, warning=FALSE}
cohort %>%
  keep(is.factor) %>%
  gather(var, value, everything()) %>%
  group_by(var, value) %>%
  summarise(n = n()) %>%
  mutate(freq = round((n / sum(n))*100, 2)) %>%
  kable(caption = "Categorial variables",
        col.names = c("Variables", "Value", "Count", "Proportion (%)")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r message=FALSE, warning=FALSE, dpi=400}
cohort %>%
  keep(is.factor) %>%
  gather() %>%
  ggplot(aes(x = value)) +
  facet_wrap(~ key, scales = "free") +
  geom_bar(fill = "#455a64") +
  labs(x = "Categorical variables", y ="")
```

# Missing values

```{r}
cohort %>%
  summarise_all(list(~sum(is.na(.)))) %>%
  gather(variable, nb_na) %>%
  arrange(desc(nb_na)) %>%
  kable(caption = "Missing values",
        col.names = c("Variables", "Missing values")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r dpi=400}
cohort %>%
  rename(
    "BMI"  = bmi_firstday,
    "Height" = height_firstday,
    "Weight" = weight_firstday,
    "Albumin" = albumin_min_firstday,
    "Bilirubin" = bilirubin_max_firstday,
    "PTT" = ptt_min_firstday
  ) %>%
  summarise_all(list(~sum(is.na(.)))) %>%
  gather(variable, nb_na) %>%
  filter(nb_na > 0) %>%
  ggplot(aes(x = reorder(variable, nb_na), y = nb_na)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = nb_na), hjust = -0.2, size = 8) +
  coord_flip() +
  labs(
    y = "Missing values",
    x = "Variables"
  ) +
  scale_fill_grey() +
  theme_bw() +
  theme(
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18)
  )
```

# Diagnosis codes

