---
title: "5.Outcomes"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(tableone)
library(knitr)
library(kableExtra)
library(Epi)
library(survival)
library(broom)
library(survminer)
library(MBESS)

cohort <- read_csv("data/cohort_shock_twavgpo2.csv")

cohort$X <- NULL
cohort$first_careunit <- factor(cohort$first_careunit)
cohort$first_wardid <- factor(cohort$first_wardid)
cohort$admission_type <- factor(cohort$admission_type)
cohort$vaso_firstday <- factor(cohort$vaso_firstday)
cohort$gender <- factor(cohort$gender)
cohort$rrt <- as.factor(cohort$rrt)
cohort$comorbidity_cardio <- factor(cohort$comorbidity_cardio)
cohort$comorbidity_vascular <- factor(cohort$comorbidity_vascular)
cohort$comorbidity_neuro <- factor(cohort$comorbidity_neuro)
cohort$comorbidity_pneumo <- factor(cohort$comorbidity_pneumo)
cohort$comorbidity_metabolic <- factor(cohort$comorbidity_metabolic)
cohort$comorbidity_renal <- factor(cohort$comorbidity_renal)
cohort$comorbidity_liver <- factor(cohort$comorbidity_liver)
cohort$comorbidity_cancer <- factor(cohort$comorbidity_cancer)
cohort$noso_vap <- factor(cohort$noso_vap)
cohort$noso_urinary <- factor(cohort$noso_urinary)
cohort$noso_cvc <- factor(cohort$noso_cvc)
cohort$noso_cvc_other <- factor(cohort$noso_cvc_other)
cohort$source_pulm <- factor(cohort$source_pulm)
cohort$source_urogyn <- factor(cohort$source_urogyn)
cohort$source_neuro <- factor(cohort$source_neuro)
cohort$source_dig <- factor(cohort$source_dig)
cohort$source_ost <- factor(cohort$source_ost)
cohort$source_ent <- factor(cohort$source_ent)
cohort$source_card <- factor(cohort$source_card)
cohort$source_skin <- factor(cohort$source_skin)
cohort$source_other <- factor(cohort$source_other)
cohort$death_icu <- factor(cohort$death_icu)
cohort$death_thirtydays <- factor(cohort$death_thirtydays)
cohort$death_hosp <- factor(cohort$death_hosp)
cohort$flag_shock <- factor(cohort$flag_shock)
cohort$hypero2 <- factor(cohort$hypero2)
cohort$hypero2 <- relevel(cohort$hypero2, ref = "normo")

# Merge Emergency and Urgent admission types
cohort$admission_type <- as.character(cohort$admission_type)
cohort$admission_type[cohort$admission_type %in% c("EMERGENCY", "URGENT")] <- "Emergency/Urgent"
cohort$admission_type <- factor(cohort$admission_type)
levels(cohort$admission_type) <- c("Elective", "Emergency/Urgent")

# Replace anonymized ages (above 300 y/o) with 89
cohort <- cohort %>%
  mutate(admission_age = replace(admission_age, admission_age > 300, 89))
```

# Baseline demographics

```{r message=FALSE, warning=FALSE}
table_demo_data <- cohort %>% 
  select(
    admission_age,
    gender,
    bmi_firstday,
    sapsii,
    sofa,
    first_careunit,
    admission_type,
    comorbidity_cardio,
    comorbidity_vascular,
    comorbidity_neuro,
    comorbidity_pneumo,
    comorbidity_metabolic,
    comorbidity_renal,
    comorbidity_liver,
    comorbidity_cancer,
    hypero2
  ) %>%
  rename(
    "Age (years)" = admission_age,
    "Male" = gender,
    "BMI (kg/m2)" = bmi_firstday,
    "SAPSII" = sapsii,
    "SOFA" = sofa,
    "First ICU (SICU)" = first_careunit,
    "Admission type (Emergency/Urgent)" = admission_type,
    "Cardiac" = comorbidity_cardio,
    "Vascular" = comorbidity_vascular,
    "Neurological" = comorbidity_neuro,
    "Pulmonary" = comorbidity_pneumo,
    "Metabolic" = comorbidity_metabolic,
    "Renal" = comorbidity_renal,
    "Liver" = comorbidity_liver,
    "Cancer" = comorbidity_cancer
  )

factor_vars <- c("Male", "First ICU (SICU)", "Admission type (Emergency/Urgent)",
                 "Cardiac", "Vascular", "Neurological", "Pulmonary", "Metabolic",
                 "Renal", "Liver", "Cancer")
nonnormal_vars <- c("SAPSII", "SOFA")

table_demo <- CreateTableOne(
  vars = names(table_demo_data)[-length(names(table_demo_data))],
  data = table_demo_data,
  factorVars = factor_vars,
  strata = "hypero2"
)
table_demo_print <- print(
  table_demo,
  nonnormal = nonnormal_vars,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r}
table_demo_all <- CreateTableOne(
  vars = names(table_demo_data)[-length(names(table_demo_data))],
  data = table_demo_data,
  factorVars = factor_vars
)
table_demo_all_print <- print(
  table_demo_all,
  nonnormal = nonnormal_vars,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r}
table_demo_final_print <- cbind(table_demo_all_print[, 1], table_demo_print[, c(1:3)])

kable(
  table_demo_final_print,
  caption = "Baseline demographics of the cohort for all patients as well as normoxemia and hyperoxemia groups",
  col.names = c("All", "Normoxia", "Hyperoxia", "p"),
  align = c("l", "c", "c", "c", "c")
) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  group_rows("Comorbidities", 9, 16)
```

# Infection sources

```{r}
table_sources_data <- cohort %>%
  select(
    source_pulm,
    source_urogyn,
    source_neuro,
    source_dig,
    source_ost,
    source_ent,
    source_card,
    source_skin,
    source_other,
    hypero2
  ) %>%
  rename(
    "Pulmonary" = source_pulm,
    "Neurological" = source_neuro,
    "Genito-urinary" = source_urogyn,
    "Digestive" = source_dig,
    "Osteo-articular" = source_ost,
    "ENT" = source_ent,
    "Cardiological" = source_card,
    "Cutaneus" = source_skin,
    "Other/Unknown" = source_other
  )
factor_vars <- c("Pulmonary", "Neurological", "Genito-urinary", "Digestive",
                 "Osteo-articular", "ENT", "Cardiological", "Cutaneus",
                 "Other/Unknown")

table_sources <- CreateTableOne(
  vars = names(table_sources_data)[-length(names(table_sources_data))],
  data = table_sources_data,
  factorVars = factor_vars,
  strata = "hypero2"
)
table_sources_print <- print(
  table_sources,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r}
table_sources_all <- CreateTableOne(
  vars = names(table_sources_data)[-length(names(table_sources_data))],
  data = table_sources_data,
  factorVars = factor_vars
)
table_sources_all_print <- print(
  table_sources_all,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r}
table_sources_final_print <- cbind(table_sources_all_print[, 1], table_sources_print[, c(1:3)])

kable(
  table_sources_final_print,
  caption = "Infection sources",
  col.names = c("All", "Normoxia", "Hyperoxia", "p"),
  align = c("l", "c", "c", "c", "c")
) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

# Biology results

```{r}
table_bio_data <- cohort %>%
  select(
    twavg_po2,
    first_po2,
    avg_24_po2,
    min_24_po2,
    max_24_po2,
    lactate_max_firstday,
    pco2_max_firstday,
    ph_min_firstday,
    bicarbonate_min_firstday,
    albumin_min_firstday,
    bilirubin_max_firstday,
    creatinine_max_firstday,
    chloride_max_firstday,
    sodium_max_firstday,
    potassium_max_firstday,
    hematocrit_min_firstday,
    hemoglobin_min_firstday,
    platelet_min_firstday,
    ptt_min_firstday,
    hypero2
  ) %>%
  rename(
    "TWA-PaO2 (mmHg)" = twavg_po2,
    "First PaO2 (mmHg)" = first_po2,
    "Average PaO2 (mmHg)" = avg_24_po2,
    "Lowest PaO2 (mmHg)" = min_24_po2,
    "Highest PaO2 (mmHg)" = max_24_po2,
    "Serum lactate (mmol/L)" = lactate_max_firstday,
    "PaCO2 (mmHg)" = pco2_max_firstday,
    "pH" = ph_min_firstday,
    "Bicarbonate (mmol/L)" = bicarbonate_min_firstday,
    "Albumin (g/dL)" = albumin_min_firstday,
    "Bilirubin (mg/dL)" = bilirubin_max_firstday,
    "Creatinine (mg/dL)" = creatinine_max_firstday,
    "Chloride (mmol/L)" = chloride_max_firstday,
    "Sodium (mmol/L)" = sodium_max_firstday,
    "Potassium (mmol/L)" = potassium_max_firstday,
    "Hematocrit (%)" = hematocrit_min_firstday,
    "Hemoglobine (g/dL)" = hemoglobin_min_firstday,
    "Platelets (G/L)" = platelet_min_firstday,
    "PTT (%)" = ptt_min_firstday
  )

table_bio <- CreateTableOne(
  vars = names(table_bio_data)[-length(names(table_bio_data))],
  data = table_bio_data,
  strata = c("hypero2")
)
table_bio_print <- print(
  table_bio,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r}
table_bio_all <- CreateTableOne(
  vars = names(table_bio_data)[-length(names(table_bio_data))],
  data = table_bio_data
)
table_bio_all_print <- print(
  table_bio_all,
  dropEqual = TRUE,
  printToggle = FALSE
)
```

```{r echo=FALSE}
table_bio_final_print <- cbind(table_bio_all_print[, 1], table_bio_print[, c(1:3)])

kable(
  table_bio_final_print,
  caption = "Biology results of the first 24 hours",
  col.names = c("All", "Normoxia", "Hyperoxia", "p"),
  align = c("l", "c", "c", "c", "c")
) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  group_rows("Arterial blood gases", 2, 9) %>%
  group_rows("Chemistry", 10, 16) %>%
  group_rows("Blood count and hemostasis", 17, 20)
```

# Univariate analyses

```{r}
table_bivariate_data <- cohort %>%
  select(
    death_icu,
    death_hosp,
    death_thirtydays,
    los_icu,
    los_hospital,
    norepinephrine_max_dose,
    norepinephrine_duration,
    rrt,
    noso_vap,
    noso_urinary,
    noso_cvc_other,
    hypero2
  ) %>%
  rename(
    "ICU LOS" = los_icu,
    "Hospital LOS" = los_hospital,
    "Norepinephrine maximum dose (mcg/kg/min)" = norepinephrine_max_dose,
    "Norepinephrine duration (hours)" = norepinephrine_duration,
    "Ventilation acquired pneumoniae" = noso_vap,
    "Urinary catheter infection" = noso_urinary,
    "Central line infection" = noso_cvc_other,
    "ICU mortality" = death_icu,
    "Hospital mortality" = death_hosp,
    "30-day mortality" = death_thirtydays
  )

vars <- c("ICU mortality", "Hospital mortality", "30-day mortality", "ICU LOS",
          "Hospital LOS", "Norepinephrine maximum dose (mcg/kg/min)",
          "Norepinephrine duration (hours)", "Ventilation acquired pneumoniae",
          "Urinary catheter infection", "Central line infection")
factor_vars <- c("Ventilation acquired pneumoniae", "Urinary catheter infection",
                 "Central line infection", "30-day mortality", "ICU mortality",
                 "Hospital mortality")
nonnormal_vars <- c("ICU LOS", "Hospital LOS")

table_bivar <- CreateTableOne(
  vars = vars,
  data = table_bivariate_data,
  strata = c("hypero2")
)
table_bivar_print <- print(
  table_bivar,
  nonnormal = nonnormal_vars,
  dropEqual = TRUE,
  printToggle = FALSE,
  smd = TRUE
)
```

```{r}
bivar_smd <- ExtractSmd(table_bivar)
smd_list <- tibble(
  smd = as.character(),
  low = as.character(),
  high = as.character(),
  txt = as.character())
smd_list <- smd_list %>% add_row(smd = "", low = "", high = "", txt = "")

for(i in 1:length(bivar_smd)){
  smd_ci <- ci.smd(smd = bivar_smd[i], n.1 = 214, n.2 = 274, conf.level = .95)
  smd_list <- smd_list %>%
    add_row(
      smd = round(bivar_smd[i], 2),
      low = round(smd_ci$Lower.Conf.Limit.smd, 2),
      high = round(smd_ci$Upper.Conf.Limit.smd, 2))
}

smd_list$txt <- paste0(smd_list$smd, " [", smd_list$low, "-", smd_list$high, "]")
smd_list[1,4] <- ""
```

```{r}
table_bivar_final_print <- cbind(table_bivar_print[, c(1:2)], smd_list$txt, table_bivar_print[, 3])
kable(
  table_bivar_final_print,
  caption = "Primary and secondary outcomes",
  col.names = c("Normoxia", "Hyperoxia", "SMD", "p"),
  align = c("l", "c", "c", "c", "c")
) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  group_rows("Primary outcome", 2, 2) %>%
  group_rows("Mortality", 3, 4) %>%
  group_rows("Length of stay", 5, 6) %>%
  group_rows("Vasopressor", 7, 8) %>%
  group_rows("Hospital acquired infections", 9, 11)
```

## Unadjusted odds ratios

```{r}
cohort$hypero2_bin <- ifelse(cohort$hypero2 == "hyper", 1, 0)
table(cohort$hypero2, cohort$hypero2_bin)
```

```{r include=FALSE}
# Death ICU
or_death_icu <- twoby2(1 - as.numeric(cohort$hypero2_bin), 1 - as.numeric(cohort$death_icu))
list_crude_or <- round(or_death_icu$measures[2, 1], 2)
list_crude_low <- round(or_death_icu$measures[2, 2], 2)
list_crude_high <- round(or_death_icu$measures[2, 3], 2)

# Death hosp
or_death_hosp <- twoby2(1 - as.numeric(cohort$hypero2_bin), 1 - as.numeric(cohort$death_hosp))
list_crude_or <- c(list_crude_or,
                   round(or_death_hosp$measures[2, 1], 2))
list_crude_low <- c(list_crude_low, round(or_death_hosp$measures[2, 2], 2))
list_crude_high <- c(list_crude_high, round(or_death_hosp$measures[2, 3], 2))

# Death 30 days
or_death_thirty <- twoby2(1 - as.numeric(cohort$hypero2_bin), 1 - as.numeric(cohort$death_thirtydays))
list_crude_or <- c(list_crude_or,
                   round(or_death_thirty$measures[2, 1], 2))
list_crude_low <- c(list_crude_low, round(or_death_thirty$measures[2, 2], 2))
list_crude_high <- c(list_crude_high, round(or_death_thirty$measures[2, 3], 2))

tab_crude_or <- tibble(
  label = c("death_icu", "death_hosp", "death_thirtydays"),
  or = list_crude_or,
  low = list_crude_low,
  high = list_crude_high,
)
tab_crude_or$IC_95 <- paste0("[", tab_crude_or$low, "-", tab_crude_or$high, "]")
```

```{r echo=FALSE}
tab_crude_or %>%
  select(label, or, IC_95) %>%
  kable(
    caption = "Unadjusted odds ratios",
    col.names = c("", "OR", "CI (95%)"),
    align = c("c", "c", "c", "c")
  ) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r echo=FALSE, fig.height=2, dpi=400}
tab_crude_or$label <- factor(tab_crude_or$label, levels = rev(tab_crude_or$label))

ggplot(tab_crude_or, aes(x = label, y = or, ymin = low, ymax = high)) +
  geom_pointrange(color = "#455a64") +
  geom_hline(yintercept = 1, lty = 2, color = "#455a64") + 
  coord_flip() +
  labs(x = "", y = "Unadjusted OR (CI 95%)") +
  theme_bw()
```

## TWA-PaO2 distribution

```{r message=FALSE, warning=FALSE, dpi=400}
ggplot(cohort) +
  geom_histogram(aes(x = twavg_po2, fill = hypero2), alpha = 0.8, bins = 75) +
  labs(
    x = "TWA-PaO2 (mmHg)",
    y = "Count"
  ) +
  scale_fill_grey(
    name = "Groups",
    labels = c("Normoxia", "Hyperoxia")
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 18)
  )
```

# Multivariate analysis

```{r}
model1 <- glm(death_icu ~ admission_age + first_careunit + hypero2_bin + sofa +
                comorbidity_liver + norepinephrine_duration + hemoglobin_min_firstday,
              data = cohort,
              family = "binomial")
summary(model1)
model1_desc <- tidy(model1)
```

```{r}
tab_reglog <- tibble(
  label = model1_desc$term,
  OR = round(exp(model1_desc$estimate), 2),
  low = round(exp(confint_tidy(model1)), 2)$conf.low,
  high = round(exp(confint_tidy(model1)), 2)$conf.high,
  p = round(model1_desc$p.value, 5)
)
tab_reglog$IC_95 <- paste0("[", tab_reglog$low, "-", tab_reglog$high, "]")

tab_reglog %>%
  select(label, OR, IC_95, p) %>%
  kable(
    caption = "Multivariate analysis of ICU mortality (logistic regression)",
    col.names = c("", "OR", "IC (95%)", "p"),
    align = c("c", "c", "c", "c")
  ) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r echo=FALSE, dpi=400}
tab_reglog$label <- factor(tab_reglog$label, levels = rev(tab_reglog$label))

ggplot(tab_reglog, aes(x = label, y = OR, ymin = low, ymax = high)) +
  geom_pointrange(color = "#455a64") +
  geom_hline(yintercept = 1, lty = 2, color = "#455a64") + 
  coord_flip() +
  labs(x = "", y = "Adjusted OR (CI 95%)") +
  theme_bw()
```

## Adjusted probability of in-ICU death by TWA-PaO2

```{r, dpi=400}
data_plot_death <- tibble(
  prob = model1$fitted.values,
  twavg_po2 = cohort$twavg_po2
)

ggplot(data_plot_death, aes(x = twavg_po2, y = prob)) +
  geom_point(size = 6, color = "#666666") +
  geom_smooth(method = loess, size = 3, color = "black") +
  labs(
    y = "Adjusted probability of in-ICU death",
    x = "Time weighted average PaO2 (mmHg)"
  ) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_bw() +
  theme(
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18)
  )
```


# Survival analysis

```{r}
fit <- survfit(Surv(time = los_icu, event = as.numeric(death_icu))~hypero2, data = cohort)
```

## Log-Rank test

```{r}
survdiff(Surv(time = los_icu, event = as.numeric(death_icu))~hypero2, data = cohort)
```

## Cox model

```{r}
model_cox <- coxph(Surv(time = los_icu, event = as.numeric(death_icu))~admission_age + first_careunit + hypero2_bin + sofa + comorbidity_liver + norepinephrine_duration + hemoglobin_min_firstday, data = cohort)
summary(model_cox)
model_cox_desc <- tidy(model_cox)
```

```{r}
tab_cox <- tibble(
  label = model_cox_desc$term,
  OR = round(exp(model_cox_desc$estimate), 2),
  low = round(exp(model_cox_desc$conf.low), 2),
  high = round(exp(model_cox_desc$conf.high), 2),
  p = round(model_cox_desc$p.value, 5)
)
tab_cox$IC_95 <- paste("[", tab_cox$low, "-", tab_cox$high, "]", sep = "")

tab_cox %>%
  select(label, OR, IC_95, p) %>%
  kable(
    caption = "Cox proportional hazard model of in-ICU mortality",
    col.names = c("", "OR", "CI (95%)", "p"),
    align = c("c", "c", "c", "c")
  ) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r echo=FALSE, dpi=400}
tab_cox$label <- factor(tab_cox$label, levels = rev(tab_cox$label))

ggplot(tab_cox, aes(x = label, y = OR, ymin = low, ymax = high)) +
  geom_pointrange(color = "#455a64") +
  geom_hline(yintercept = 1, lty = 2, color = "#455a64") + 
  coord_flip() +
  labs(x = "", y = "OR (IC 95%)") +
  theme_bw()
```

## Kaplan-Meier curve

```{r, dpi=400}
ggsurvplot(
  fit, data = cohort,
  pval = "Hazard ratio 0.83, 95% CI [0.61-1.14]\np = 0.259",
  pval.size = 6,
  pval.coord = c(0.2, 0.10),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable(),
  tables.y.text.col = FALSE,
  linetype = "strata",
  palette = "grey",
  xlab = "Days since admission",
  legend = c(0.85, 0.7),
  legend.title = "",
  legend.labs = c("Normoxia", "Hyperoxia"),
  fontsize = 5,
  font.x = 16,
  font.y = 16,
  font.tickslab = 14,
  font.legend = 14,
  ggtheme = theme_classic()
)
```
